### ISSUE TITLE
API failures

### ISSUE THREAD

**Issue by nick-verida** [verida/network-data-api#9]
We are getting 

```
{"message":"Error: Failed to get number of active DIDs","status":"fail"}
```

I added some logging and see the following when running locally:

```
Error: Failed to get number of active DIDs
    at /Users/nlothian/dev/verida/network-data-api/node_modules/@verida/vda-did-resolver/dist/activeDIDCount.js:74:27
    at step (/Users/nlothian/dev/verida/network-data-api/node_modules/@verida/vda-did-resolver/dist/activeDIDCount.js:33:23)
    at Object.throw (/Users/nlothian/dev/verida/network-data-api/node_modules/@verida/vda-did-resolver/dist/activeDIDCount.js:14:53)
    at rejected (/Users/nlothian/dev/verida/network-data-api/node_modules/@verida/vda-did-resolver/dist/activeDIDCount.js:6:65)
```

**Comment by nick-verida** [comment]
According to https://github.com/verida/metrics/actions this has been failing since around Oct 23

**Comment by nick-verida** [comment]
It started failing Oct 23, which is puzzling.

There are commits to https://github.com/verida/blockchain-contracts/blob/develop/VDA-DID-Registry/contracts/VeridaDIDRegistryV2.sol around a week before that but I don't know how to check when that was deployed.

**Comment by nick-verida** [comment]
Unclear why this was failing, but today it is working again. 

https://github.com/verida/verida-js/issues/356 has been raised to get better error reporting added to `vda-did-resolver`
